name: Deploy Backend to Cloudflare Workers

on:
  push:
    branches: [main, master]
    paths:
      - "backend/**"
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-button]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Disable wrangler telemetry
        run: npx wrangler telemetry disable

      - name: Check if deploy button trigger
        id: check-deploy-button
        run: |
          if [[ "${{ github.event_name }}" == "repository_dispatch" && "${{ github.event.action }}" == "deploy-button" ]]; then
            echo "is_deploy_button=true" >> $GITHUB_OUTPUT
          else
            echo "is_deploy_button=false" >> $GITHUB_OUTPUT
          fi

      - name: Create D1 Database
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "检查并创建D1数据库..."
          DATABASE_LIST=$(npx wrangler d1 list --json 2>/dev/null || echo "[]")
          EXISTING_DB=$(echo "$DATABASE_LIST" | jq -r '.[] | select(.name=="cloudpaste-db") | .uuid')

          if [ -n "$EXISTING_DB" ]; then
            echo "✅ 找到D1数据库: $EXISTING_DB"
            DATABASE_ID=$EXISTING_DB
          else
            CREATE_OUTPUT=$(npx wrangler d1 create cloudpaste-db 2>&1)
          
            if echo "$CREATE_OUTPUT" | grep -q "Successfully created DB"; then
              DATABASE_ID=$(echo "$CREATE_OUTPUT" | grep -oP "database_id = \"\K[^\"]+")
              if [ -z "$DATABASE_ID" ]; then
                DATABASE_ID=$(echo "$CREATE_OUTPUT" | grep -oP "([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})")
              fi
            else
              LIST_OUTPUT=$(npx wrangler d1 list --json 2>/dev/null || echo "[]")
              DATABASE_ID=$(echo "$LIST_OUTPUT" | jq -r '.[] | select(.name=="cloudpaste-db") | .uuid')
          
              if [ -z "$DATABASE_ID" ]; then
                echo "❌ 无法创建或找到D1数据库"
                exit 1
              fi
            fi
          fi

          sed -i -E "s/(database_id = \")[^\"]+(\"\s*$)/\1$DATABASE_ID\2/" wrangler.toml
          echo "database_id=$DATABASE_ID" >> $GITHUB_ENV

      - name: Initialize D1 Database with schema
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler d1 execute cloudpaste-db --file=./schema.sql || echo "表可能已存在，继续部署"

      - name: Set ENCRYPTION_SECRET environment variable
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # 检查密钥是否已存在
          SECRET_EXISTS=$(npx wrangler secret list 2>&1 | grep -q "ENCRYPTION_SECRET" && echo "yes" || echo "no")

          if [ "$SECRET_EXISTS" = "yes" ]; then
            echo "✅ ENCRYPTION_SECRET 已存在，跳过创建步骤"
          else
            # 如果不存在，则创建密钥
            if [[ -n "${{ secrets.ENCRYPTION_SECRET }}" ]]; then
              ENCRYPTION_VALUE="${{ secrets.ENCRYPTION_SECRET }}"
            else
              ENCRYPTION_VALUE=$(openssl rand -base64 32)
            fi

            set +e
            echo "$ENCRYPTION_VALUE" | npx wrangler secret put ENCRYPTION_SECRET
            SECRET_RESULT=$?
            set -e
          
            if [ $SECRET_RESULT -ne 0 ]; then
              echo "❌ 设置机密失败"
              exit 1
            fi
          
            echo "✅ ENCRYPTION_SECRET 已成功创建"
          fi

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "./backend"
          command: deploy

      - name: Display Success Information
        if: steps.check-deploy-button.outputs.is_deploy_button == 'true' && success()
        run: |
          echo "===================================================="
          echo "🎉 CloudPaste 后端已成功部署！"
          echo "===================================================="
          echo "后续步骤："
          echo "1. 部署前端应用"
          echo "2. 访问您的Worker URL进行初始化"
          echo "3. 登录默认账户 (admin/admin123) 并立即修改密码"
          echo "4. 配置S3兼容存储"
          echo "===================================================="

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ 部署成功！"
          else
            echo "❌ 部署失败！"
          fi
